### ISSUE TITLE
OBS pipewire window capture crashing hyprland

### ISSUE THREAD

**Issue by vesdev** [hyprwm/xdg-desktop-portal-hyprland#196]
steps to reproduce:
* capture a window
* switch to scene 2
* close window
* switch to scene 1
hyprland crashes or shows the last frame of the window before it closed
going to scene 2 and back to 1 will crash

<details>
  <summary>crash report</summary>

  ```
  --------------------------------------------
     Hyprland Crash Report
  --------------------------------------------
  Sorry, didn't mean to...
  
  Hyprland received signal 11 (Segmentation fault)
  
  Version: f590505daf90dfb4059289a906863b59663e70a6
  Tag: 
  
  System info:
	  System name: Linux
	  Node name: nixos-pc
	  Release: 6.7.6-cachyos
	  Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri Feb 23 08:51:59 UTC 2024
  
  GPU:
	  05:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU106 [GeForce RTX 2060 Rev. A] [10de:1f08] (rev a1) (prog-if 00 [VGA controller])
  0d:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c5) (prog-if 00 [VGA controller])
  
  
  os-release:
	  ANSI_COLOR="1;34"
	  BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
	  BUILD_ID="24.05.20240229.ebe6e80"
	  DOCUMENTATION_URL="https://nixos.org/learn.html"
	  HOME_URL="https://nixos.org/"
	  ID=nixos
	  IMAGE_ID=""
	  IMAGE_VERSION=""
	  LOGO="nix-snowflake"
	  NAME=NixOS
	  PRETTY_NAME="NixOS 24.05 (Uakari)"
	  SUPPORT_URL="https://nixos.org/community.html"
	  VERSION="24.05 (Uakari)"
	  VERSION_CODENAME=uakari
	  VERSION_ID="24.05"
	  
  
  
  Backtrace:
	  #0 | /run/current-system/sw/bin/Hyprland(_Z12getBacktracev+0x48) [0x583458]
		  getBacktrace()
		  ??:?
	  #1 | /run/current-system/sw/bin/Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x6b5) [0x52bba5]
		  CrashReporter::createAndSaveCrash(int)
		  ??:?
	  #2 | /run/current-system/sw/bin/Hyprland(_Z25handleUnrecoverableSignali+0x44) [0x4a31f4]
		  handleUnrecoverableSignal(int)
		  ??:?
	  #3 | /nix/store/8mc30d49ghc8m5z96yz39srlhg5s9sjj-glibc-2.38-44/lib/libc.so.6(+0x3deb0) [0x7daebea54eb0]
		  ??
		  ??:0
	  #4 | /nix/store/1iixlnbx1rh7mrwdr5javns99cylgikr-wayland-1.22.0/lib/libwayland-server.so.0(+0xd822) [0x7daebf7e4822]
		  ??
		  ??:0
	  #5 | /nix/store/1iixlnbx1rh7mrwdr5javns99cylgikr-wayland-1.22.0/lib/libwayland-server.so.0(+0x8c4b) [0x7daebf7dfc4b]
		  ??
		  ??:0
	  #6 | /nix/store/1iixlnbx1rh7mrwdr5javns99cylgikr-wayland-1.22.0/lib/libwayland-server.so.0(wl_event_loop_dispatch+0xa2) [0x7daebf7e28f2]
		  ??
		  ??:0
	  #7 | /nix/store/1iixlnbx1rh7mrwdr5javns99cylgikr-wayland-1.22.0/lib/libwayland-server.so.0(wl_display_run+0x25) [0x7daebf7e0455]
		  ??
		  ??:0
	  #8 | /run/current-system/sw/bin/Hyprland(main+0x7a2) [0x48e022]
		  main
		  ??:?
	  #9 | /nix/store/8mc30d49ghc8m5z96yz39srlhg5s9sjj-glibc-2.38-44/lib/libc.so.6(+0x280ce) [0x7daebea3f0ce]
		  ??
		  ??:0
	  #10 | /nix/store/8mc30d49ghc8m5z96yz39srlhg5s9sjj-glibc-2.38-44/lib/libc.so.6(__libc_start_main+0x89) [0x7daebea3f189]
		  ??
		  ??:0
	  #11 | /run/current-system/sw/bin/Hyprland(_start+0x25) [0x4a3055]
		  _start
		  ??:?
  
  
  Log tail:
  [LOG] cursorImage request: surface 32f6a60
  [LOG] Searching for matching rules for com.obsproject.Studio (title: OBS 30.0.2 - Profile: Untitled - Scenes: Untitled)
  [LOG] Set keyboard focus to surface 3438200, with [Window 31e5c70: title: "ves@nixos-pc: ~/dev/vueko"]
  [LOG] Searching for matching rules for kitty (title: ves@nixos-pc: ~/dev/vueko)
  [LOG] cursorImage request: shape 9
  [LOG] Callback 2d62c80 -> 2d62c78, CWLSurface removed.
  [LOG] CWLSurface 2d62c18 called destroy()
  [LOG] cursorImage request: shape 9
  [LOG] [Window 331de60: title: "App", class: vueko] unmapped
  [LOG] Unregistered late callbacks XWL
  [LOG] Callback 331e0f8 -> 331e0f0, XWayland Window Late removed.
  [LOG] Callback 331e300 -> 331e2f8, XWayland Window Late removed.
  [LOG] Callback 331e028 -> 331e020, XWayland Window Late removed.
  [LOG] Callback 331e230 -> 331e228, Xwayland Window Late removed.
  [LOG] Callback 331e1c8 -> 331e1c0, Xwayland Window Late removed.
  [LOG] Framebuffer created, status 36053
  [LOG] Unmapped was not focused, ignoring a refocus.
  [LOG] Callback 331e438 -> 331e430, Toplevel removed.
  [LOG] Callback 331e3d0 -> 331e3c8, Toplevel removed.
  [LOG] Callback 331e4a0 -> 331e498, Toplevel removed.
  [LOG] Callback 331e6e8 -> 331e6e0, CWLSurface removed.
  [LOG] CWLSurface 331e680 called destroy()
  [LOG] Callback 331df58 -> 331df50, CWindow removed.
  [LOG] Searching for matching rules for kitty (title: ves@nixos-pc: ~/dev/vueko)
  [LOG] Callback 331def0 -> 331dee8, XWayland Window removed.
  [LOG] Callback 331de88 -> 331de80, XWayland Window removed.
  [LOG] [Window 331de60: title: "App", class: ] destroyed, queueing.
  [LOG] XWayland class raw: vueko
  [LOG] Callback 331dfc0 -> 331dfb8, XWayland Window removed.
  [LOG] Callback 331e368 -> 331e360, XWayland Window removed.
  [LOG] Callback 331e508 -> 331e500, XWayland Window removed.
  [LOG] Callback 331e570 -> 331e568, XWayland Window removed.
  [LOG] Callback 331e5d8 -> 331e5d0, XWayland Window removed.
  [xwayland/xwm.c:1623] xcb error: op ChangeProperty (no minor), code Window (no extension), sequence 905, value 4194307
  [xwayland/xwm.c:1623] xcb error: op DeleteProperty (no minor), code Window (no extension), sequence 906, value 4194307
  [LOG] Destroyed 32f0dd0 tearing hint
  [LOG] Callback 32f24f8 -> 32f24f0, TearingController removed.
  [LOG] Callback 32f2490 -> 32f2488, TearingController removed.
  [LOG] Cleanup: destroyed a window
  [LOG] Searching for matching rules for kitty (title: ves@nixos-pc: ~/dev/vueko)
  [LOG] Set keyboard focus to surface 3439140, with [Window 3300340: title: "OBS 30.0.2 - Profile: Untitled - Scenes: Untitled"]
  [LOG] Searching for matching rules for com.obsproject.Studio (title: OBS 30.0.2 - Profile: Untitled - Scenes: Untitled)
  [LOG] cursorImage request: surface 32f6a60
  [LOG] Registered signal for owner 2d62c18: 32f6d78 -> 2d62c58 (owner: CWLSurface)
  [LOG] CWLSurface 2d62c18 called init()
  [LOG] cursorImage request: surface 32f6a60
  [LOG] cursorImage request: surface 32f6a60
  [LOG] cursorImage request: surface 32f6a60
  [LOG] cursorImage request: surface 32f6a60
  [ERR] Client requested sharing of window handle 0 which does not exist!
  [LOG] Searching for matching rules for com.obsproject.Studio (title: OBS 30.0.2 - Profile: Untitled - Scenes: Untitled)
  [LOG] Set keyboard focus to surface 3438200, with [Window 31e5c70: title: "ves@nixos-pc: ~/dev/vueko"]
  [LOG] Searching for matching rules for kitty (title: ves@nixos-pc: ~/dev/vueko)
  [LOG] cursorImage request: shape 9
  [LOG] Callback 2d62c80 -> 2d62c78, CWLSurface removed.
  [LOG] CWLSurface 2d62c18 called destroy()
  [LOG] cursorImage request: shape 9
  [LOG] Searching for matching rules for kitty (title: ves@nixos-pc: ~/dev/vueko)
  [LOG] Set keyboard focus to surface 3439140, with [Window 3300340: title: "OBS 30.0.2 - Profile: Untitled - Scenes: Untitled"]
  [LOG] Searching for matching rules for com.obsproject.Studio (title: OBS 30.0.2 - Profile: Untitled - Scenes: Untitled)
  [LOG] cursorImage request: surface 32f6a60
  [LOG] Registered signal for owner 2d62c18: 32f6d78 -> 2d62c58 (owner: CWLSurface)
  [LOG] CWLSurface 2d62c18 called init()
  ```
</details>

**Comment by vaxerski** [comment]
looks like a hyprland bug, can you try getting an asan trace?

https://wiki.hyprland.org/Crashes-and-Bugs/#building-the-wayland-stack-with-asan

**Comment by vesdev** [comment]
```
=================================================================
==152703==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x000000de31cf bp 0x7ffffffedde0 sp 0x7ffffffedaf0 T0)
==152703==The signal is caused by a READ memory access.
==152703==Hint: address points to the zero page.
    #0 0xde31cf in wl_closure_invoke ../src/connection.c:1027
    #1 0xdd127d in wl_client_connection_data ../src/wayland-server.c:440
    #2 0xdd75e8 in wl_event_source_fd_dispatch ../src/event-loop.c:113
    #3 0xddc38d in wl_event_loop_dispatch ../src/event-loop.c:1105
    #4 0xdd46e2 in wl_display_run ../src/wayland-server.c:1519
    #5 0x6bdd1b in CCompositor::startCompositor() /home/ves/dev/Hyprland/src/Compositor.cpp:623
    #6 0xb1c154 in main /home/ves/dev/Hyprland/src/main.cpp:111
    #7 0x7ffff683f0cd in __libc_start_call_main (/nix/store/8mc30d49ghc8m5z96yz39srlhg5s9sjj-glibc-2.38-44/lib/libc.so.6+0x280cd) (BuildId: e948d07286607c37a05e967820db9a8138b5ab72)
    #8 0x7ffff683f188 in __libc_start_main_impl (/nix/store/8mc30d49ghc8m5z96yz39srlhg5s9sjj-glibc-2.38-44/lib/libc.so.6+0x28188) (BuildId: e948d07286607c37a05e967820db9a8138b5ab72)
    #9 0x6b2454 in _start (/home/ves/dev/Hyprland/build/Hyprland+0x6b2454)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ../src/connection.c:1027 in wl_closure_invoke
==152703==ABORTING
```
